---
# run pre tasks on any machine
- hosts: localhost
  tags: always
  connection: local
  become: true
  pre_tasks:
    - name: Update package cache and install updates
      tags: always
      apt: 
        upgrade: dist
        update_cache: yes
  
# switch this out to roles later on
  tasks: 
  - name: install packages
    apt: 
      name: 
        - htop
        - python3-psutil

  - name: Copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: Set wallpaper
    become_user: lee
    dconf: 
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: Set wallpaper position
    become_user: lee
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Copy .bashrc file
    copy: 
      src: files/bashrc
      dest: /home/lee/.bashrc
      owner: lee
      group: lee
      
      
  - name: install visual studio code 
    apt:
      name: code
      state: latest

  - name: Remove geary package
    apt: 
      name: geary
      state: absent
      
  - name: Install cmatrix
    apt:
      name: cmatrix
      state: latest
      
  - name: Install neofetch
    apt:
      name: neofetch
      
  - name: Install evolution 
    apt:
      name: evolution
              
# run clean up on all machines
- hosts: localhost
  become: true 
  connection: local
  tasks:
  
  - name: Cleanup package cache 
    tags: always
    apt:
      autoclean: yes
    changed_when: false

  - name: Autoremove orphan packages
    tags: always
    apt:
      autoremove: yes
      purge: yes

