- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - "{{ dns_utils_package}}"
      - htop
      - "{{ lm_sensors_package }}"
      - lsof
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - "{{ rename_package }}"
      - screen
      - sshfs
      - traceroute
      - wget
      - whois
      - zsh
      - mlocate
